import Head from "next/head";
import { Layout } from "./layout";
import { Map } from "./Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-6xl font-semibold">DPM</h1>
        <Map />
        <Sidebar />
      </Layout>
    </>
  );
}

const Sidebar = () => {
  return (
    <aside>
      <div></div>
    </aside>
  );
};
